package formats

import (
	"encoding/json"
	"strings"
	"time"

	"github.com/requi/encore/internal/domain"
)

// extendedTimeLayouts are the shapes `ts` has been observed in, most common
// first. Spotify documents RFC 3339 in UTC, but exports generated by older
// tooling have dropped the zone or the "T".
var extendedTimeLayouts = []string{
	time.RFC3339Nano,
	time.RFC3339,
	"2006-01-02T15:04:05",
	"2006-01-02 15:04:05",
	"2006-01-02T15:04",
	"2006-01-02 15:04",
}

// localURIPrefix marks a file the listener played from their own disk. It has no
// catalogue identity and never will, so it is skipped rather than rejected.
const localURIPrefix = "spotify:local:"

// ExtendedParser reads the "Extended streaming history" export:
// Streaming_History_Audio_*.json, and endsong_*.json from before the rename.
type ExtendedParser struct{}

// NewExtendedParser builds the parser. It holds no state, so one instance may be
// shared by every file in a job.
func NewExtendedParser() *ExtendedParser { return &ExtendedParser{} }

// Format identifies the export this parser reads.
func (p *ExtendedParser) Format() domain.ImportFormat { return domain.FormatExtended }

// extendedRecord is one element of an extended streaming history file, covering
// every field name the export has used since 2018.
//
// Fields Encore does not store are still declared. Decoding them explicitly is
// what keeps a value of an unexpected type in a field nobody cares about from
// costing the listener a real play.
type extendedRecord struct {
	TS          flexString `json:"ts"`
	Platform    flexString `json:"platform"`
	MsPlayed    flexInt    `json:"ms_played"`
	ConnCountry flexString `json:"conn_country"`

	// Username identified the account in pre-2021 exports; Encore already knows
	// whose import this is, so it is read and discarded.
	Username flexString `json:"username"`
	// The network address and client string are read for tolerance and then
	// dropped on the floor. Encore has nowhere to put them and no reason to keep
	// a listener's IP history in a listening-statistics database.
	IPAddrDecrypted    flexString `json:"ip_addr_decrypted"`
	IPAddr             flexString `json:"ip_addr"`
	UserAgentDecrypted flexString `json:"user_agent_decrypted"`

	TrackName  flexString `json:"master_metadata_track_name"`
	ArtistName flexString `json:"master_metadata_album_artist_name"`
	AlbumName  flexString `json:"master_metadata_album_album_name"`
	TrackURI   flexString `json:"spotify_track_uri"`

	EpisodeName     flexString `json:"episode_name"`
	EpisodeShowName flexString `json:"episode_show_name"`
	EpisodeURI      flexString `json:"spotify_episode_uri"`

	AudiobookTitle        flexString `json:"audiobook_title"`
	AudiobookURI          flexString `json:"audiobook_uri"`
	AudiobookChapterURI   flexString `json:"audiobook_chapter_uri"`
	AudiobookChapterTitle flexString `json:"audiobook_chapter_title"`

	ReasonStart flexString `json:"reason_start"`
	ReasonEnd   flexString `json:"reason_end"`

	Shuffle          flexBool `json:"shuffle"`
	Skipped          flexBool `json:"skipped"`
	Offline          flexBool `json:"offline"`
	OfflineTimestamp flexInt  `json:"offline_timestamp"`
	IncognitoMode    flexBool `json:"incognito_mode"`
}

// Parse converts one raw record into a listening event.
//
// The order of the checks is deliberate. What the record *is* (a podcast, a local
// file) is decided before whether it is *well-formed*, so that a broken timestamp
// on an episode nobody wants to import is reported as a skip rather than as a
// reject the user then has to interpret.
func (p *ExtendedParser) Parse(raw json.RawMessage, minMsPlayed int32) (Record, error) {
	var rec extendedRecord
	if rej := decodeObject(raw, &rec); rej != nil {
		return Record{}, rej
	}
	if rec.empty() {
		return Record{}, reject(domain.RejectUnknownShape,
			"object carries no extended streaming history fields")
	}
	if what, ok := rec.nonMusic(); ok {
		return Record{Skip: skipf(domain.SkipNotMusic, "%s", what)}, nil
	}

	ms, rej := msPlayed(rec.MsPlayed, "ms_played")
	if rej != nil {
		return Record{}, rej
	}

	ts := rec.TS.String()
	if ts == "" {
		return Record{}, reject(domain.RejectMissingTimestamp, "ts is absent")
	}
	endedAt, ok := parseTimestamp(ts, extendedTimeLayouts)
	if !ok {
		return Record{}, reject(domain.RejectInvalidTimestamp, "ts %q is not a recognised timestamp", ts)
	}

	uri := rec.TrackURI.String()
	if strings.HasPrefix(strings.ToLower(uri), localURIPrefix) {
		return Record{Skip: skipf(domain.SkipLocalFile, "local file %q", uri)}, nil
	}
	if ms < minMsPlayed {
		return Record{Skip: skipf(domain.SkipBelowMinimum,
			"ms_played %d is below the %d ms minimum", ms, minMsPlayed)}, nil
	}

	identity, rej := extendedIdentity(uri, rec.ArtistName.String(), rec.TrackName.String())
	if rej != nil {
		return Record{}, rej
	}

	return Record{Listen: domain.Listen{
		PlayedAt:  domain.StartFromEnd(endedAt, ms),
		Precision: domain.PrecisionSecond,
		Identity:  identity,
		MsPlayed:  ms,
		Source:    domain.SourceExtended,

		TrackName:  rec.TrackName.String(),
		ArtistName: rec.ArtistName.String(),

		Platform:    rec.Platform.String(),
		ConnCountry: rec.ConnCountry.String(),
		ReasonStart: rec.ReasonStart.String(),
		ReasonEnd:   rec.ReasonEnd.String(),
		Shuffle:     rec.Shuffle.Ptr(),
		Skipped:     rec.Skipped.Ptr(),
		Offline:     rec.Offline.Ptr(),
		Incognito:   rec.IncognitoMode.Ptr(),
	}}, nil
}

// extendedIdentity prefers the track URI and falls back to the names.
//
// The fallback matters: exports routinely contain plays whose spotify_track_uri
// is null while the metadata names survive, and treating those as unusable would
// silently drop months of history. A names-only identity converges on the real
// track later, when the alias resolver finds it.
func extendedIdentity(uri, artist, title string) (domain.TrackIdentity, *domain.RejectError) {
	if id, ok := domain.TrackIDFromURI(uri); ok {
		return domain.TrackIdentityFromID(id), nil
	}
	identity, rej := namesIdentity(artist, title)
	if rej != nil && uri != "" {
		return domain.TrackIdentity{}, reject(domain.RejectMissingTrack,
			"spotify_track_uri %q is not a track reference and the names are unusable", uri)
	}
	return identity, rej
}

// nonMusic reports whether the record describes something other than a music
// track. Modern exports interleave podcasts and audiobooks with music in the same
// file, and neither belongs in listening statistics about tracks and artists.
func (r extendedRecord) nonMusic() (string, bool) {
	switch {
	case r.EpisodeURI.String() != "" || r.EpisodeName.String() != "" || r.EpisodeShowName.String() != "":
		return "podcast episode " + firstNonEmpty(
			r.EpisodeName.String(), r.EpisodeShowName.String(), r.EpisodeURI.String()), true
	case r.AudiobookURI.String() != "" || r.AudiobookTitle.String() != "" ||
		r.AudiobookChapterURI.String() != "" || r.AudiobookChapterTitle.String() != "":
		return "audiobook " + firstNonEmpty(
			r.AudiobookTitle.String(), r.AudiobookChapterTitle.String(),
			r.AudiobookURI.String(), r.AudiobookChapterURI.String()), true
	}
	return "", false
}

// empty reports whether the object has none of the format's fields at all, which
// means the file is not an extended streaming history however it was labelled.
func (r extendedRecord) empty() bool {
	return r.TS.String() == "" && !r.MsPlayed.Present &&
		r.TrackURI.String() == "" && r.TrackName.String() == "" &&
		r.ArtistName.String() == "" && r.AlbumName.String() == "" &&
		r.EpisodeName.String() == "" && r.EpisodeShowName.String() == "" && r.EpisodeURI.String() == "" &&
		r.AudiobookTitle.String() == "" && r.AudiobookURI.String() == "" &&
		r.AudiobookChapterTitle.String() == "" && r.AudiobookChapterURI.String() == "" &&
		r.Platform.String() == "" && r.ConnCountry.String() == ""
}
